version: '3.8'
services:
<<<<<<< HEAD
    db:
        image: 'sdabizljevic3920rn/database:1.0'
        container_name: db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
	restart: unless-stopped
        networks:
            - backend-network
    
    redis:
        image: 'redis:latest'
        container_name: rdb
        ports:
            - "6379:6379"
	restart: unless-stopped
	networks:
            - backend-network
    
    user-service:
        image: vzivanovic/user-service:4.0
        ports:
            - "8080:8080"
        container_name: user-service 
        restart: unless-stopped
        networks:
            - backend-network

    banka-service:
        image: vzivanovic/banka-service:4.0
        ports:
            - "8082:8082"
        container_name: banka-service 
        restart: unless-stopped
        networks:
            - backend-network
    
    berza-service:
        image: vzivanovic/berza-service:4.0
        ports:
            - "8081:8081"
        container_name: berza-service
        restart: unless-stopped
        networks:
            - backend-network
        
networks:
    backend-network:
        driver: bridge
=======
  db10:
    image: 'sdabizljevic3920rn/database:1.0'
    container_name: db10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

#version: '2'
#
#services:
#  db1:
#    image: 'postgres:latest'
#    container_name: db
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_MULTIPLE_DATABASES= banka4-banka-service,banka4-berza-service,banka4-user-service
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=123
#  db2:
#    image: 'postgres:latest'
#    container_name: db
#    ports:
#      - "5433:5432"
#    environment:
#      - POSTGRES_DB=banka4-berza-service
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=123
#  db3:
#    image: 'postgres:latest'
#    container_name: db
#    ports:
#      - "5434:5432"
#    environment:
#      - POSTGRES_DB=banka4-user-service
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=123
  redis:
    image: 'redis:latest'
    container_name: rdb
    ports:
      - "6379:6379"
>>>>>>> upstream/main
