version: '3.8'
services:
  db10:
    image: 'sdabizljevic3920rn/database:1.0'
    container_name: db10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

#version: '2'
#
#services:
#  db1:
#    image: 'postgres:latest'
#    container_name: db
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_MULTIPLE_DATABASES= banka4-banka-service,banka4-berza-service,banka4-user-service
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=123
#  db2:
#    image: 'postgres:latest'
#    container_name: db
#    ports:
#      - "5433:5432"
#    environment:
#      - POSTGRES_DB=banka4-berza-service
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=123
#  db3:
#    image: 'postgres:latest'
#    container_name: db
#    ports:
#      - "5434:5432"
#    environment:
#      - POSTGRES_DB=banka4-user-service
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=123
  redis:
    image: 'redis:latest'
    container_name: rdb
    ports:
      - "6379:6379"